### ISSUE TITLE
Wrap into easy-to-use CLI utility

### ISSUE THREAD

**Issue by josephsamela** [gregstarr/pychop3d#26]
`pychop3d` would be much easier to use (and distribute) if it could be invoked from the commandline. Would also solve #17. Something like this...

```bash
$ python main.py ./path/to/mesh.stl
```

...ideally you wouldn't need to edit source code to use the tool. Any configuration settings would be passed as commandline arguments. Omitted arguments would be replaced with sensible defaults. For example...

```bash
$ python main.py --beam_width 3 --scale_factor 5 ./path/to/mesh.stl
```

Python [argparse](https://docs.python.org/3/library/argparse.html) could be a good solution.

**Comment by gregstarr** [comment]
Thanks Joe, 
I had intended for yaml files to be the way that the user specifies their settings. I am uploading two example configs which should run consistently. These configs will have comments so the user can see what settings they have control over.

**Comment by gregstarr** [comment]
My above comment and the commits I am about to make will address this issue and #25
