### ISSUE TITLE
Ability to chop parts that fit in print bed

### ISSUE THREAD

**Issue by afshawnlotfi** [gregstarr/pychop3d#39]
Hi I build pretty big parts in my 3D printer that techichally fit in the bed but I would prefer to have them in smaller attachable pieces because each part is a ton a plastic and if something goes wrong in the print the whole thing is a waste. Is that possible with this algorithm? Should I just make the bed size smaller for a workaround in the config?

**Comment by gregstarr** [comment]
Yes that should work, let me know if you run into trouble

**Comment by gregstarr** [comment]
@afshawnlotfi did this work for you? Can I close this issue?

**Comment by afshawnlotfi** [comment]
Yes
